name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Setup build environment
        run: |
          sudo pip3 install virtualenv
          ./esp-idf/install.sh
      - name: Build
        run: |
          source ./esp-idf/export.sh
          idf.py build
