name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: install esp-idf toolchain
        run: |
          sudo apt-get install -y -qqq libncurses5-dev gperf
          ./esp-idf/install.sh
      - name: build
        run: |
          . ./setup-env.sh
          make -j$(nproc)
